CREATE TABLE weather_facts (
    fact_id SERIAL PRIMARY KEY,
    city_id INTEGER REFERENCES dim_city(city_id),
    date_id INTEGER REFERENCES dim_date(date_id),
    weather_id INTEGER REFERENCES dim_weather(weather_id),
    sunrise TIMESTAMP,
    sunset TIMESTAMP,
    temp_C REAL,
    temp_min_C REAL,
    temp_max_C REAL,
    feels_like_C REAL,
    pressure REAL,
    humidity REAL,
    wind_speed REAL,
    wind_deg REAL,
    wind_gust REAL,
    cloudiness REAL,
    precipitation_prob REAL,
    rain_1d REAL,
    summary TEXT,
    extracted_at TIMESTAMP,
    is_ideal_temp BOOLEAN,
    is_low_rain BOOLEAN,
    is_low_wind BOOLEAN,
    is_ideal_humidity BOOLEAN,
    comfort_score REAL,
    is_ideal_day BOOLEAN
);