name: DAG Validation

on:
  push:
    paths:
      - 'airflow/dags/**'
  pull_request:
    paths:
      - 'airflow/dags/**'

jobs:
  test-dags:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_HOME: ${{ github.workspace }}/airflow
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Airflow
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow==3.0.1

      - name: Initialize Airflow
        run: |
          mkdir -p $AIRFLOW_HOME
          airflow db init

      - name: Validate DAGs syntax
        run: |
          for file in airflow/dags/*.py; do
            echo "Checking $file"
            python -m py_compile "$file"
            python -c "import sys; sys.path.insert(0, 'airflow/dags'); import $(basename "$file" .py)"
          done
